if [[ -z "$DISPLAY" && -z "$WAYLAND_DISPLAY" && "${XDG_VTNR:-}" == "1" ]]; then
    if command -v start-hyprland >/dev/null 2>&1; then
        exec start-hyprland
    elif command -v uwsm >/dev/null 2>&1; then
        exec uwsm start hyprland-uwsm.desktop
    fi
fi

if [[ -z "$ZELLIJ" ]]; then
    if [[ "$ZELLIJ_AUTO_ATTACH" == "true" ]]; then
        zellij attach -c
    else
        zellij
    fi

    if [[ "$ZELLIJ_AUTO_EXIT" == "true" ]]; then
        exit
    fi
fi

bindkey '^@' autosuggest-accept
bindkey '^[^M' autosuggest-execute
bindkey "^k" history-beginning-search-backward
bindkey "^j" history-beginning-search-forward

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#7a8596'

# Add ssh key to agent if not already added
ssh-add -l > /dev/null || ssh-add

# Source zsh config when creating a new nix shell
if [ "$IN_NIX_SHELL" = "impure" ]; then
  source ~/.zshrc
fi
